@api = http://localhost:4000/api/notificaciones
GET {{api}}

POST {{api}}
Content-Type: application/json

{
    "id": 1,
    "titulo": "titulo",
    "descripcion": "descripcion",
    "fecha": "fecha",
    "hora": "hora",
    "estado": "estado",
    "id_usuario": 1
}